apiVersion: v1
kind: PersistentVolume
metadata:
  name: eventstore-pv
  labels:
    type: local
spec:
  storageClassName: eventstore
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s/data/eventstore"