apiVersion: v1
kind: PersistentVolume
metadata:
  name: appointmentdb-pv
  labels:
    type: local
spec:
  storageClassName: appointmentdb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/Shared/k8s/data/appointmentdb"